### ISSUE TITLE
CompilationContext with fields?

### ISSUE THREAD

**Issue by dfdx** [femtomc/Mixtape.jl#17]
Is it possible to store state inside of a custom `CompilationContext`? I tried this:

```julia
struct MyMix <: CompilationContext
    state::MyState
end
...
call(foo; ctx=MyMix(state))
```
But it gives an error `MethodError: no method matching MyMix()` due to [lines](https://github.com/JuliaCompilerPlugins/Mixtape.jl/blob/master/src/Mixtape.jl#L589):

```julia
entry = jit(f.instance, TT; 
    ctx = ctx(), opt = true, optlevel = T)
```
I guess we can replace it with `ctx = ctx` to avoid the error, but is it even legal to use the state here?

Just for reference, IRTools [does support it](https://fluxml.ai/IRTools.jl/latest/dynamo/#Contexts-1), but I don't really understand their internals.

**Comment by femtomc** [comment]
@dfdx sorry I didn't get back to you on this.

This is mostly about passing things to the `AbstractInterpreter` which `Mixtape` uses. But in general, this is not advised. The way that `Mixtape` operates is different than `IRTools` dynamos (for instance). If you want to insert a context or collecting state, the recommended way to do this would be with a pass that does so.

It's not valid to collect state during the inference process -- indeed, it's not even something that would be accessible at runtime. The best you can do it collect information about inference. If you want some sort of runtime context state, you can do it with a pass.

**Comment by dfdx** [comment]
Thanks for the clarification!
